name: espaco_infantil
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-290.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  image_picker: ^0.8.7
  intl: ^0.18.0
  flutter_sequence_animation: 
  shared_preferences: ^2.0.18
  get: ^4.6.5
  cached_network_image: ^3.2.3
  hive: ^2.2.3
  path_provider: ^2.0.13
  sqflite: ^2.2.6
  firebase_core: 
  http:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
